### ISSUE TITLE
How to perform multi-GPU training?

### ISSUE THREAD

**Issue by ddwwbb2001** [mazurowski-lab/ContourDiff#1]
Hi,
I have been trying to run the ContourDiff model on multiple GPUs to speed up the training process, but couldn't find any instructions in the README file. I wonder if you have any suggestions or plans for enabling multi-GPU training?

**Comment by gogochen07** [comment]
Hey,

Thanks for your interest in our work!

I just updated the README file and code to enable multi-gpu training.

**Comment by ddwwbb2001** [comment]
Thank you so much :）
