### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by hayatol-lw** [mazurowski-lab/ContourDiff#2]
Hello, could you please provide the version details of the Python libraries used in your code? I encountered the following error while running the code, which indicates that it was caused by an incompatible torch version.
![屏幕截图 2024-08-25 234719](https://github.com/user-attachments/assets/237ad77f-782d-4190-bf7e-6a545dc8f592)

**Comment by gogochen07** [comment]
Thanks for interesting in our work!

I used torch 2.4.0+cu121.
